#ifndef SIMULATION_ENGINE_ASTRONOMICAL_ALGORITHMS_H
#define SIMULATION_ENGINE_ASTRONOMICAL_ALGORITHMS_H

/**
 * The gravitational constant in newton.
 */
#define GRAVITATIONAL_CONSTANT 6.67430e-11

#endif //SIMULATION_ENGINE_ASTRONOMICAL_ALGORITHMS_H
